version: "2.1"
services:
  openssh-server:
    image: rastasheep/ubuntu-sshd:14.04
    container_name: 03_sys-module
    hostname: 03_sys-module
    environment:
      - ROOT_PASSWORD=root
    ports:
      - "10003:22"
    cap_add:
      - "SYS_MODULE"
    restart: unless-stopped
