version: "2.1"
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server
    container_name: 03_sys-module
    hostname: 03_sys-module
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SUDO_ACCESS=true 
      - PASSWORD_ACCESS=true 
      - USER_PASSWORD=password
      - USER_NAME=attacker
    ports:
      - 10002:2222
    cap_add:
      - "SYS_MODULE"
    restart: unless-stopped
