version: "2.1"
services:
  openssh-server:
    image: mulinbc/sshd 
    container_name: 03_sys-module
    hostname: 03_sys-module
    environment:
      - ROOT_PASSWORD=root
    ports:
      - "10003:22"
    cap_add:
      - "SYS_MODULE"
    volumes:
      - "/lib/modules:/lib/modules"
      - "/usr/src:/usr/src"
    restart: unless-stopped
